language: python
python:
    - "3.6"
install:
    - pip install pipenv==11.0.0
    - pipenv install -e .
script:
    - pipenv run py.test tests
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - docker build -t $DOCKER_IMAGE_NAME .
    - if [ ! -z "$TRAVIS_TAG"  ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; fi && docker push $DOCKER_IMAGE_NAME
env:
    - DOCKER_IMAGE_NAME=soasme/zetanote
